# Generated by Django 4.2.7 on 2023-11-16 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='https://vk-wiki.ru/wp-content/uploads/2019/04/male-user-profile-picture.png', null=True, upload_to='users/avatars', verbose_name='Аватарка')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('started_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата назначения')),
                ('user', models.OneToOneField(blank=True, default=None, help_text='<small class="text-muted">Тут лежит "ссылка" на модель пользователя</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Модель пользователя')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ('-user', 'avatar'),
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Идея по улучшению бизнеса',
                'verbose_name_plural': 'Идеи по улучшению бизнеса',
                'ordering': ('date_created',),
            },
        ),
    ]
