# Generated by Django 4.2.7 on 2023-11-23 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_resume_vacancy_delete_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hr_comment',
            field=models.CharField(default='no comment', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='hr_rating',
            field=models.IntegerField(blank=True, default=0, help_text='Введите рейтинг от 1 до 10.', validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1.'), django.core.validators.MaxValueValidator(10, message='Рейтинг не может быть больше 10.')]),
        ),
    ]
