# Generated by Django 4.2.7 on 2023-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_resume_hr_comment_resume_hr_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/'),
        ),
    ]
