# Generated by Django 4.2.7 on 2023-12-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_resume_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='hr_comment',
            field=models.CharField(blank=True, default='no comment', max_length=500, null=True),
        ),
    ]
